spring.application.name=doc-request-system
# Server Port
server.port=8080

# MySQL Database Settings
spring.datasource.url=jdbc:mysql://localhost:3306/barangay_db?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=09062063128Jeff
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Telegram Bot Configuration
telegram.bot.token=8899447670:AAEf2lB22lM9eFM9aCVDZLGhL-bXhq068LA